In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("student.csv")

In [3]:
df.head()

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [4]:
df = df.iloc[:,2:]

In [5]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)
X_train.shape, X_test.shape


((40, 2), (10, 2))

In [7]:
X_train.sample()

review education
31   Poor    School

In [8]:
from sklearn.preprocessing import OrdinalEncoder

In [9]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [10]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [11]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [12]:
X_train

array([[2., 2.],
       [1., 2.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 1.],
       [0., 1.],
       [0., 1.],
       [2., 2.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [0., 0.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [2., 1.],
       [2., 0.],
       [0., 1.],
       [2., 2.],
       [0., 0.],
       [1., 1.],
       [2., 1.],
       [1., 1.],
       [1., 0.],
       [0., 2.],
       [1., 2.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [0., 2.],
       [0., 0.],
       [1., 2.],
       [2., 2.],
       [2., 0.],
       [1., 0.],
       [0., 2.],
       [2., 0.]])

In [13]:
X_test

array([[0., 2.],
       [1., 0.],
       [2., 0.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [2., 2.],
       [1., 1.],
       [2., 1.],
       [1., 1.]])

# LabelEncoding

this encode technique is only use to encode output column of dataset

In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y_train)

LabelEncoder()

In [15]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [16]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [17]:
y_train

array([1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0])

In [ ]:
y